version: '3.1'
services:   
  master:
    image: resulguldibi/master  
    ports:
      - 6379:6379 
    volumes:
      - ./docker-infra/master/data:/data        
  slave:
    image: resulguldibi/slave
    command: redis-server --slaveof master 6379
    links:
      - master      
    volumes:
      - ./docker-infra/slave/data:/data    
  sentinel:
    image: resulguldibi/sentinel    
    command: bash -c 'cp -rp /etc/redis/sentinel.conf /etc/redis/sentinel.actual.conf && sed -i "s/\$$SENTINEL_PORT/${SENTINEL_PORT}/g" /etc/redis/sentinel.actual.conf && sed -i "s/\$$SENTINEL_FAILOVER/${SENTINEL_FAILOVER}/g" /etc/redis/sentinel.actual.conf && sed -i "s/\$$SENTINEL_QUORUM/${SENTINEL_QUORUM}/g" /etc/redis/sentinel.actual.conf && sed -i "s/\$$SENTINEL_DOWN_AFTER/${SENTINEL_DOWN_AFTER}/g" /etc/redis/sentinel.actual.conf && chown redis:redis /etc/redis/sentinel.actual.conf && chmod -R 0777 /etc/redis && chmod -R 0777 /tmp && redis-server /etc/redis/sentinel.actual.conf --sentinel'
    
    links:
      - master
    ports:
      - 26379:26379      
    volumes:
      - ./docker-infra/sentinel/conf:/etc/redis
      - ./docker-infra/sentinel/data:/data
    environment:
      - SENTINEL_DOWN_AFTER=${SENTINEL_DOWN_AFTER}               
      - SENTINEL_FAILOVER=${SENTINEL_FAILOVER}   
      - SENTINEL_QUORUM=${SENTINEL_QUORUM}   
      - SENTINEL_PORT=${SENTINEL_PORT}
  go-client:
    image: resulguldibi/sentinel-go-client
    container_name: sentinel-go-client 