version: '3.1'
services:   
  master:
    image: redis:6.2  
    ports:
      - 6379:6379      
  slave:
    image: redis:6.2
    command: redis-server --slaveof master 6379
    links:
      - master          
  sentinel:
    image: redis:6.2    
    command: bash -c "cp -rp /etc/redis/sentinel.conf /etc/redis/sentinel.actual.conf && sed -i \"s/\$$SENTINEL_PORT/$${SENTINEL_PORT}/g\" /etc/redis/sentinel.actual.conf && sed -i \"s/\$$SENTINEL_FAILOVER/$${SENTINEL_FAILOVER}/g\" /etc/redis/sentinel.actual.conf && sed -i \"s/\$$SENTINEL_QUORUM/$${SENTINEL_QUORUM}/g\" /etc/redis/sentinel.actual.conf && sed -i \"s/\$$SENTINEL_DOWN_AFTER/$${SENTINEL_DOWN_AFTER}/g\" /etc/redis/sentinel.actual.conf && chown redis:redis /etc/redis/sentinel.actual.conf && chmod -R 0777 /etc/redis && chmod -R 0777 /tmp && redis-server /etc/redis/sentinel.actual.conf --sentinel"
    links:
      - master
    ports:
      - 26379:26379      
    volumes:
      - ./conf:/etc/redis
    environment:
      - SENTINEL_DOWN_AFTER=5000               
      - SENTINEL_FAILOVER=10000
      - SENTINEL_QUORUM=1
      - SENTINEL_PORT=26379